name: portfolio_site
description: "Responsive zweisprachige Flutter-Portfolio-Seite von Jessica Ernst."
publish_to: 'none' # private Repo, nicht pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # UI & Layout
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  collection: ^1.19.1
  auto_hyphenating_text: ^0.3.0

  # State Management
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: any

  # Utils
  shared_preferences: ^2.5.3
  logging: ^1.3.0

  # Firebase (nur Analytics für Web)
  firebase_core: ^3.12.1
  firebase_analytics: ^11.4.4

  # Routing
  go_router: ^15.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints & Code-Gen
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  freezed: ^2.5.0
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  flutter_gen_runner: ^5.8.0
  riverpod_generator: ^2.6.3
  custom_lint: ^0.7.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true